import { createCipheriv, createDecipheriv, randomBytes } from 'node:crypto';
import { Buffer } from 'node:buffer';
import { URL } from 'node:url';
import { lookup } from 'node:dns/promises';
import { DomainError } from '@flight-platform/shared';
import { SecretCipher, UrlPolicy } from '../../application/ports';

const privateIp = (ip: string) => ip === '::1' || ip.startsWith('127.') || ip.startsWith('10.') || ip.startsWith('192.168.') || ip.startsWith('169.254.') || /^172\.(1[6-9]|2\d|3[01])\./.test(ip) || ip.startsWith('fc') || ip.startsWith('fd') || ip.startsWith('fe80:');
export class WebhookUrlPolicy implements UrlPolicy { constructor(private readonly production: boolean) {} async assertSafe(raw: string): Promise<void> { let url: URL; try { url = new URL(raw); } catch { throw new DomainError('VALIDATION_FAILED'); } if ((this.production && url.protocol !== 'https:') || (!this.production && !['https:', 'http:'].includes(url.protocol)) || url.username || url.password || ['localhost', 'localhost.localdomain'].includes(url.hostname.toLowerCase())) throw new DomainError('VALIDATION_FAILED'); const answers = await lookup(url.hostname, { all: true, verbatim: true }).catch(() => { throw new DomainError('VALIDATION_FAILED'); }); if (!answers.length || answers.some((answer) => privateIp(answer.address))) throw new DomainError('VALIDATION_FAILED'); } }
export class AesGcmCipher implements SecretCipher { private readonly key: Buffer; constructor(encoded: string) { this.key = Buffer.from(encoded, 'base64'); if (this.key.length !== 32) throw new Error('WEBHOOK_SECRET_ENCRYPTION_KEY must decode to 32 bytes'); } encrypt(value: string): string { const iv = randomBytes(12); const cipher = createCipheriv('aes-256-gcm', this.key, iv); const encrypted = Buffer.concat([cipher.update(value, 'utf8'), cipher.final()]); return Buffer.concat([iv, cipher.getAuthTag(), encrypted]).toString('base64'); } decrypt(value: string): string { const raw = Buffer.from(value, 'base64'); const decipher = createDecipheriv('aes-256-gcm', this.key, raw.subarray(0, 12)); decipher.setAuthTag(raw.subarray(12, 28)); return Buffer.concat([decipher.update(raw.subarray(28)), decipher.final()]).toString('utf8'); } }
