/* global __dirname, console, process */
/* Usage: INTERNAL_API_KEY=... node scripts/smoke.cjs host:443 https://receiver.example/webhook */
const grpc = require('@grpc/grpc-js'); const protoLoader = require('@grpc/proto-loader'); const { randomUUID } = require('node:crypto'); const { join } = require('node:path');
const [target, receiverUrl] = process.argv.slice(2); const key = process.env.INTERNAL_API_KEY;
if (!target || !receiverUrl || !key) { console.error('Usage: INTERNAL_API_KEY=... node scripts/smoke.cjs host:443 https://receiver.example/webhook'); process.exit(2); }
const root = join(__dirname, '..', '..', '..', 'contracts', 'proto'); const definition = protoLoader.loadSync(join(root, 'flightplatform/webhooks/v1/webhooks.proto'), { includeDirs: [root], keepCase: false, defaults: true, arrays: true, objects: true }); const api = grpc.loadPackageDefinition(definition).flightplatform.webhooks.v1;
const client = new api.WebhooksService(target, target.startsWith('localhost') || target.startsWith('127.') ? grpc.credentials.createInsecure() : grpc.credentials.createSsl()); const metadata = new grpc.Metadata(); metadata.set('x-internal-key', key); metadata.set('x-owner-id', `smoke-${randomUUID()}`); metadata.set('x-role', 'system');
const call = (method, request) => new Promise((resolve, reject) => client[method](request, metadata, (error, response) => error ? reject(error) : resolve(response)));
(async () => { try { await call('createSubscription', { ownerId: metadata.get('x-owner-id')[0], url: receiverUrl, events: ['booking.confirmed'], secret: `smoke-${randomUUID()}` }); console.log('OK CreateSubscription'); const published = await call('publishEvent', { ownerId: metadata.get('x-owner-id')[0], payload: { eventId: randomUUID(), eventType: 'booking.confirmed', occurredAt: new Date().toISOString(), apiVersion: '1.5.0.0', data: { status: 'CONFIRMED' } } }); console.log(`OK PublishEvent ${published.eventId}`); await call('dispatchPending', {}); console.log('OK DispatchPending'); } catch (error) { console.error(`FAIL ${error.details || error.message}`); process.exitCode = 1; } finally { client.close(); } })();
