import process from 'node:process'; import { existsSync } from 'node:fs'; import { randomUUID } from 'node:crypto'; import { Writable } from 'node:stream'; import { afterAll, beforeAll } from '@jest/globals'; import { credentials, loadPackageDefinition, Metadata, ServiceError } from '@grpc/grpc-js'; import { loadSync } from '@grpc/proto-loader'; import { PrismaClient } from '../../src/infrastructure/persistence/prisma-client/client';
import { createLogger, createTicketingServer, findProtoRoot } from '../../src/infrastructure/grpc/server'; import { join } from 'node:path';
import { PrismaTicketStore } from '../../src/infrastructure/persistence/prisma-ticket-store';
import { TicketStore } from '../../src/application/ports';
const key = 'k'.repeat(40); const bookingId = randomUUID(); const ownerId = `ticket-test-${randomUUID()}`;
describe('Ticketing gRPC integration (TKT-01, TKT-05, TKT-07)', () => {
  let prisma: PrismaClient; let app: Awaited<ReturnType<typeof createTicketingServer>>; let client: Record<string, (...args: unknown[]) => void>; const logs: string[] = [];
  const call = <T>(method: string, input: unknown, role = 'system') => new Promise<T>((resolve, reject) => { const md = new Metadata(); md.set('x-internal-key', key); md.set('x-role', role); client[method](input, md, (e: ServiceError | null, r: T) => e ? reject(e) : resolve(r)); });
  beforeAll(async () => { const env = join(process.cwd(), 'microservices', 'ticketing-service', '.env'); if (existsSync(env)) process.loadEnvFile(env); if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL is required for ticketing integration tests'); prisma = new PrismaClient(); const port = 30000 + Math.floor(Math.random() * 10000); const sink = new Writable({ write(chunk, _encoding, callback) { logs.push(String(chunk)); callback(); } }); const logger = createLogger(sink); logger.level = 'debug'; app = await createTicketingServer({ url: `127.0.0.1:${port}`, internalApiKey: key, prisma, logger, config: { prefix: '999', failMode: 'none' } }); await app.listen(); const root = findProtoRoot(); const def = loadSync(join(root, 'flightplatform/ticketing/v1/ticketing.proto'), { includeDirs: [root], keepCase: false, enums: String, longs: Number, defaults: true, arrays: true, objects: true }); const pkg = loadPackageDefinition(def) as unknown as { flightplatform: { ticketing: { v1: { TicketingService: new (a: string, b: unknown) => typeof client } } } }; client = new pkg.flightplatform.ticketing.v1.TicketingService(`127.0.0.1:${port}`, credentials.createInsecure()); });
  const createdBookings = [bookingId];
  afterAll(async () => { if (prisma && process.env.DATABASE_URL) { await prisma.issuanceRequest.deleteMany({ where: { bookingId: { in: createdBookings } } }); await prisma.ticket.deleteMany({ where: { bookingId: { in: createdBookings } } }); } (client as unknown as { close?: () => void } | undefined)?.close?.(); await app?.close(); await prisma?.$disconnect(); });
  const request = (requestId = randomUUID(), targetBookingId = bookingId) => ({ bookingId: targetBookingId, ownerId, requestId, passengers: [{ passengerId: 'p-1', passengerType: 'ADULT', firstName: 'A', lastName: 'B' }], itineraries: [{ itineraryId: 'i-1', segments: [{ segmentId: 's-1' }, { segmentId: 's-2' }] }] });
  it('issues a ticket per passenger with coupons and replays idempotently', async () => { const r = await call<{ tickets: Array<{ eTicketNumber: string; segments: unknown[] }> }>('IssueTickets', request('same')); expect(r.tickets).toHaveLength(1); expect(r.tickets[0].eTicketNumber).toMatch(/^999\d{10}$/); expect(r.tickets[0].segments).toHaveLength(2); const replay = await call<{ tickets: Array<{ eTicketNumber: string }> }>('IssueTickets', request('same')); expect(replay.tickets[0].eTicketNumber).toBe(r.tickets[0].eTicketNumber); const list = await call<{ tickets: unknown[] }>('ListTickets', { bookingId, ownerId }, 'customer'); expect(list.tickets).toHaveLength(1); });
  it('serializes concurrent delivery of the same issuance request', async () => { const concurrentBooking = randomUUID(); createdBookings.push(concurrentBooking); const input = request('concurrent', concurrentBooking); const [left, right] = await Promise.all([call<{ tickets: Array<{ ticketId: string }> }>('IssueTickets', input), call<{ tickets: Array<{ ticketId: string }> }>('IssueTickets', input)]); expect(left.tickets).toHaveLength(1); expect(right.tickets).toHaveLength(1); expect(right.tickets[0].ticketId).toBe(left.tickets[0].ticketId); expect(await prisma.ticket.count({ where: { bookingId: concurrentBooking } })).toBe(1); });
  it('TKT-04: generates 1,000 unique e-ticket numbers in the required 13-digit format', async () => { const bulkBooking = randomUUID(); try { const passengers = Array.from({ length: 1000 }, (_, i) => ({ passengerId: `bulk-${i}` })); const tickets = await new PrismaTicketStore(prisma).issue(bulkBooking, 'bulk-numbers', ownerId, passengers, ['bulk-segment'], '999', 'none', new Date()); const numbers = tickets.map((ticket) => ticket.props.eTicketNumber); expect(numbers).toHaveLength(1000); expect(new Set(numbers).size).toBe(1000); expect(numbers.every((number) => /^999\d{10}$/.test(number ?? ''))).toBe(true); } finally { await prisma.issuanceRequest.deleteMany({ where: { bookingId: bulkBooking } }); await prisma.ticket.deleteMany({ where: { bookingId: bulkBooking } }); } }, 30_000);
  it('hides another owner as an empty ticket list', async () => { const r = await call<{ tickets: unknown[] }>('ListTickets', { bookingId, ownerId: 'other-owner' }, 'customer'); expect(r.tickets).toEqual([]); });
  it('rejects missing key and malformed request', async () => { await expect(new Promise((resolve, reject) => client.ListTickets({ bookingId: 'bad', ownerId }, new Metadata(), (e: ServiceError | null, r: unknown) => e ? reject(e) : resolve(r)))).rejects.toMatchObject({ code: 16 }); await expect(call('ListTickets', { bookingId: 'bad', ownerId }, 'customer')).rejects.toMatchObject({ code: 3 }); });
  it('persists FAILED with failureReason when fail mode is always', async () => { const failedBooking = randomUUID(); try { const tickets = await new PrismaTicketStore(prisma).issue(failedBooking, 'fail-mode', ownerId, [{ passengerId: 'failed-passenger' }], ['s-failed'], '999', 'always', new Date()); expect(tickets).toHaveLength(1); expect(tickets[0].props).toMatchObject({ status: 'FAILED', failureReason: 'TICKET_ISSUANCE_FAILED' }); } finally { await prisma.issuanceRequest.deleteMany({ where: { bookingId: failedBooking } }); await prisma.ticket.deleteMany({ where: { bookingId: failedBooking } }); } });
  it('voids, refunds and reissues issued tickets through their command RPCs', async () => {
    const voidBooking = randomUUID(), refundBooking = randomUUID(), reissueBooking = randomUUID(); createdBookings.push(voidBooking, refundBooking, reissueBooking);
    await call('IssueTickets', request('void', voidBooking)); const voided = await call<{ tickets: Array<{ status: string }> }>('VoidTickets', { bookingId: voidBooking, ownerId }); expect(voided.tickets).toEqual([expect.objectContaining({ status: 'VOIDED' })]);
    await call('IssueTickets', request('refund', refundBooking)); const refunded = await call<{ tickets: Array<{ status: string }> }>('RefundTickets', { bookingId: refundBooking, ownerId }); expect(refunded.tickets).toEqual([expect.objectContaining({ status: 'REFUNDED' })]);
    await call('IssueTickets', request('reissue', reissueBooking)); const reissued = await call<{ tickets: Array<{ status: string; eTicketNumber?: string; segments: Array<{ segmentId: string }> }> }>('ReissueTickets', { bookingId: reissueBooking, ownerId, newItineraries: [{ itineraryId: 'new', segments: [{ segmentId: 'new-segment' }] }] }); expect(reissued.tickets).toEqual(expect.arrayContaining([expect.objectContaining({ status: 'VOIDED' }), expect.objectContaining({ status: 'ISSUED', eTicketNumber: expect.stringMatching(/^999\d{10}$/), segments: [expect.objectContaining({ segmentId: 'new-segment' })] })]));
  });
  it('enforces the security baseline: role and owner failures reveal no resource', async () => {
    await expect(call('IssueTickets', request('customer-role'), 'customer')).rejects.toMatchObject({ code: 7, details: 'PERMISSION_DENIED' });
    const issued = await call<{ tickets: Array<{ ticketId: string }> }>('ListTickets', { bookingId, ownerId }, 'customer');
    await expect(call('GetTicket', { bookingId, ownerId: 'another-owner', ticketId: issued.tickets[0].ticketId }, 'customer')).rejects.toMatchObject({ code: 5, details: 'NOT_FOUND' });
  });
  it('TKT-SEC-03: forced internal errors are generic and PII is redacted from logs', async () => {
    const piiBooking = randomUUID(); createdBookings.push(piiBooking); const piiRequest = request('pii-log', piiBooking); piiRequest.passengers[0].firstName = 'AlicePrivate'; piiRequest.passengers[0].lastName = 'SurnamePrivate'; await call('IssueTickets', piiRequest); const joinedLogs = logs.join(''); expect(joinedLogs).not.toContain('AlicePrivate'); expect(joinedLogs).not.toContain('SurnamePrivate'); expect(joinedLogs).toContain('[REDACTED]');
    const failingStore: TicketStore = { issue: async () => [], forBooking: async () => { throw new Error('forced internal secret detail'); }, get: async () => null, updateAll: async () => [] }; const port = 41000 + Math.floor(Math.random() * 1000); const faulty = await createTicketingServer({ url: `127.0.0.1:${port}`, internalApiKey: key, prisma, store: failingStore }); await faulty.listen(); const FaultClient = client.constructor as unknown as new (address: string, credentials: unknown) => Record<string, (...args: unknown[]) => void>; const faultClient = new FaultClient(`127.0.0.1:${port}`, credentials.createInsecure()); try { await expect(new Promise((resolve, reject) => { const md = new Metadata(); md.set('x-internal-key', key); md.set('x-role', 'customer'); faultClient.ListTickets({ bookingId, ownerId }, md, (error: ServiceError | null, result: unknown) => error ? reject(error) : resolve(result)); })).rejects.toMatchObject({ code: 13, details: 'INTERNAL_ERROR' }); } finally { (faultClient as unknown as { close?: () => void }).close?.(); await faulty.close(); }
  });
});
