/* global __dirname */
import { existsSync } from 'node:fs'; import { dirname, join, resolve } from 'node:path'; import process from 'node:process'; import { Buffer } from 'node:buffer';
import { DynamicModule, INestMicroservice, Module } from '@nestjs/common'; import { NestFactory } from '@nestjs/core'; import { MicroserviceOptions, Transport } from '@nestjs/microservices'; import { sendUnaryData, Server, ServerUnaryCall } from '@grpc/grpc-js'; import { service as healthService } from 'grpc-health-check'; import { z } from 'zod';
import { buildRequestContext, InternalKeyInterceptor, loggerOptions, safeGrpcError, validate } from '@flight-platform/shared';
import pino, { Logger as PinoLogger } from 'pino';
import { PrismaClient } from '../persistence/prisma-client/client'; import { WebhookUseCases } from '../../application/webhook-use-cases'; import { WebhookStore } from '../../application/ports'; import { PrismaWebhookStore } from '../persistence/prisma-webhook-store'; import { AesGcmCipher, WebhookUrlPolicy } from '../security/webhook-security'; import { FetchHttpPoster } from '../clients/fetch-http-poster'; import { WebhooksExceptionFilter, WebhooksLoggingInterceptor } from './filters'; import { WEBHOOKS_DEPS, WebhooksController } from './webhooks.controller';
export const GRPC_PACKAGE = 'flightplatform.webhooks.v1';
export const findProtoRoot = (from: string = __dirname): string => { for (let d = resolve(from); ; d = dirname(d)) { const p = join(d, 'contracts', 'proto'); if (existsSync(p)) return p; if (dirname(d) === d) throw new Error('contracts/proto not found'); } };
@Module({}) class WebhooksModule { static register(useCases: WebhookUseCases): DynamicModule { return { module: WebhooksModule, controllers: [WebhooksController], providers: [{ provide: WEBHOOKS_DEPS, useValue: useCases }] }; } }
const health = z.object({ service: z.string().max(255) });
const addHealth = (server: Server, key: string) => server.addService({ Check: healthService.Check }, { Check: (call: ServerUnaryCall<{ service: string }, { status: string }>, cb: sendUnaryData<{ status: string }>) => { try { buildRequestContext(call.metadata, key); validate(health, call.request); cb(null, { status: 'SERVING' }); } catch (error) { cb(safeGrpcError(error)); } } });
export function createLogger(destination?: pino.DestinationStream): PinoLogger { return pino({ ...loggerOptions, level: process.env.LOG_LEVEL ?? 'info' }, destination); }
export async function createWebhooksServer(options: { url: string; internalApiKey: string; encryptionKey: string; prisma: PrismaClient; store?: WebhookStore; logger?: PinoLogger; production?: boolean }): Promise<INestMicroservice> { if (Buffer.byteLength(options.internalApiKey) < 32) throw new Error('INTERNAL_API_KEY must be at least 32 bytes'); const backoffMinutes = (process.env.WEBHOOK_BACKOFF_MINUTES ?? '1,5,15,60,180,720').split(',').map(Number); const useCases = new WebhookUseCases(options.store ?? new PrismaWebhookStore(options.prisma), new WebhookUrlPolicy(options.production ?? process.env.NODE_ENV === 'production'), new AesGcmCipher(options.encryptionKey), new FetchHttpPoster(), { timeoutMs: Number(process.env.WEBHOOK_TIMEOUT_MS ?? 5000), backoffMinutes, production: options.production ?? process.env.NODE_ENV === 'production' }); const root = findProtoRoot(); const app = await NestFactory.createMicroservice<MicroserviceOptions>(WebhooksModule.register(useCases), { transport: Transport.GRPC, logger: ['error', 'warn'], options: { url: options.url, package: GRPC_PACKAGE, protoPath: join(root, 'flightplatform/webhooks/v1/webhooks.proto'), loader: { includeDirs: [root], keepCase: false, enums: String, longs: Number, defaults: true, arrays: true, objects: true }, onLoadPackageDefinition: (_: unknown, server: Server) => addHealth(server, options.internalApiKey) } }); app.useGlobalInterceptors(new InternalKeyInterceptor(options.internalApiKey), new WebhooksLoggingInterceptor(options.logger ?? createLogger())); app.useGlobalFilters(new WebhooksExceptionFilter()); return app; }
