import { createHmac, randomUUID } from 'node:crypto'; import { Buffer } from 'node:buffer';
import { WebhookUseCases } from '../../src/application/webhook-use-cases';
import { HttpPoster, UrlPolicy, WebhookStore } from '../../src/application/ports';
import { Delivery, Subscription, WebhookPayload } from '../../src/domain/webhook';
import { AesGcmCipher } from '../../src/infrastructure/security/webhook-security';

/* global beforeEach */
const key = Buffer.alloc(32, 7).toString('base64'); const now = new Date('2026-10-07T12:00:00.000Z'); const ctx = { ownerId: 'owner-a', role: 'system', correlationId: 'test' };
class Store implements WebhookStore { subscriptions: Subscription[] = []; deliveries: Delivery[] = []; async createSubscription(input: Subscription) { this.subscriptions.push(input); return input; } async listSubscriptions(ownerId: string) { return this.subscriptions.filter((s) => s.ownerId === ownerId); } async deleteSubscription(id: string, ownerId: string) { const at = this.subscriptions.findIndex((s) => s.id === id && s.ownerId === ownerId); if (at < 0) return false; this.subscriptions.splice(at, 1); return true; } async activeFor(ownerId: string, eventType: string) { return this.subscriptions.filter((s) => s.ownerId === ownerId && s.active && s.events.includes(eventType as never)); } async getSubscription(id: string) { return this.subscriptions.find((s) => s.id === id) ?? null; } async createDeliveries(eventId: string, payload: WebhookPayload, ids: string[], at: Date) { this.deliveries.push(...ids.map((subscriptionId) => ({ id: randomUUID(), eventId, subscriptionId, payload, status: 'PENDING' as const, attempts: 0, nextAttemptAt: at }))); } async claimPending(at: Date) { return this.deliveries.filter((d) => d.status === 'PENDING' && d.nextAttemptAt <= at).map((d) => ({ ...d, status: 'PROCESSING' as const })); } async delivered(id: string) { this.deliveries.find((d) => d.id === id)!.status = 'DELIVERED'; } async failed(id: string, attempts: number, nextAttemptAt: Date, terminal: boolean) { const d = this.deliveries.find((item) => item.id === id)!; d.status = terminal ? 'FAILED' : 'PENDING'; d.attempts = attempts; d.nextAttemptAt = nextAttemptAt; } }
const policy: UrlPolicy = { assertSafe: jest.fn().mockResolvedValue(undefined) }; const cipher = new AesGcmCipher(key);
describe('WebhookUseCases', () => { let store: Store; let poster: HttpPoster; let useCases: WebhookUseCases; beforeEach(() => { store = new Store(); poster = { post: jest.fn().mockResolvedValue(204) }; useCases = new WebhookUseCases(store, policy, cipher, poster, { timeoutMs: 5000, backoffMinutes: [1, 5, 15, 60, 180, 720], production: false }, () => now); });
  it('masks secrets and scopes deletion to the owner', async () => { const created = await useCases.create(ctx, { ownerId: 'owner-a', url: 'https://hooks.example.test/a', events: ['booking.confirmed'], secret: 'my-secret-1234' }); expect(created.secret).toBe('****1234'); expect((await useCases.list(ctx, { ownerId: 'owner-a' }))[0].secret).toBe('****1234'); await expect(useCases.delete(ctx, { id: created.id, ownerId: 'owner-b' })).rejects.toMatchObject({ code: 'NOT_FOUND' }); });
  it('creates one delivery for each matching active subscription and signs its stable event', async () => { await useCases.create(ctx, { ownerId: 'owner-a', url: 'https://hooks.example.test/1', events: ['booking.confirmed'], secret: 'signing-secret' }); await useCases.create(ctx, { ownerId: 'owner-a', url: 'https://hooks.example.test/2', events: ['booking.confirmed'], secret: 'signing-secret' }); const eventId = randomUUID(); await useCases.publish(ctx, { ownerId: 'owner-a', payload: { eventId, eventType: 'booking.confirmed' } }); expect(store.deliveries).toHaveLength(2); await expect(useCases.dispatch(ctx, {})).resolves.toBe(2); const call = (poster.post as jest.Mock).mock.calls[0]; expect(call[1]).toContain(eventId); const timestamp = Math.floor(now.getTime() / 1000); expect(call[2]['x-flight-signature']).toBe(`t=${timestamp},v1=${createHmac('sha256', 'signing-secret').update(`${timestamp}.${call[1]}`).digest('hex')}`); });
  it('reschedules a failed delivery using the first configured backoff', async () => { const created = await useCases.create(ctx, { ownerId: 'owner-a', url: 'https://hooks.example.test/1', events: ['booking.confirmed'], secret: 'secret' }); await useCases.publish(ctx, { ownerId: 'owner-a', payload: { eventType: 'booking.confirmed' } }); (poster.post as jest.Mock).mockResolvedValueOnce(500); await useCases.dispatch(ctx, {}); expect(store.deliveries[0]).toMatchObject({ subscriptionId: created.id, status: 'PENDING', attempts: 1, nextAttemptAt: new Date(now.getTime() + 60_000) }); });
});
